@startuml

'用例图
'主要用于描述系统的行为及各种功能之间的关系，是描述参与者(Actor)与用例以及用例与用例之间关系的图。
'用例图 = 参与者 + 用例 + 关系
'用例图显示谁将是相关的用户、用户希望系统提供什么服务以及用户需要为系统提供的服务。
'用例图最常用来描述系统以及子系统。
'描述系统功能特性，与实现无关

''''用例图包含三个元素：
'参与者(Actor) 可以是系统或者用户
'用例(Use Case) 代表系统使用的动作
'关联关系(Association) 参与者与用例之间最简单常用的关系



''''''''''' 定义Actor的两种方式
:User: as user
actor Admin as admin

''''''''''' 定义用例的两种方式
(open browser) as ob
'''添加用例描述 download是用例的名称
usecase download as "
下载软件
==
使用浏览器"

'''''''''''' 连接角色和用例
user -> ob
ob -> download : search

@enduml